[BROKEN] Tolyabic Drill
Currently, placing down the mining drill causes this crash:

java.lang.NullPointerException: Unexpected error
	at supersymmetry.common.metatileentities.multi.electric.MetaTileEntityMiningDrill.createStructurePattern(MetaTileEntityMiningDrill.java:67)
	at gregtech.api.metatileentity.multiblock.MultiblockControllerBase.reinitializeStructurePattern(MultiblockControllerBase.java:74)
	at gregtech.api.metatileentity.multiblock.MultiblockControllerBase.onPlacement(MultiblockControllerBase.java:70)
	at gregtech.api.block.machines.BlockMachine.onBlockPlacedBy(BlockMachine.java:266)
	at net.minecraft.item.ItemBlock.placeBlockAt(ItemBlock.java:205)
	at gregtech.api.block.machines.MachineItemBlock.placeBlockAt(MachineItemBlock.java:85)
	at net.minecraft.item.ItemBlock.onItemUse(ItemBlock.java:57)
	at net.minecraft.item.ItemStack.onItemUse(ItemStack.java:201)
	at net.minecraft.client.multiplayer.PlayerControllerMP.processRightClickBlock(PlayerControllerMP.java:499)
	at net.minecraft.client.Minecraft.rightClickMouse(Minecraft.java:1694)
	at net.minecraft.client.Minecraft.processKeyBinds(Minecraft.java:2381)
	at net.minecraft.client.Minecraft.runTickKeyboard(Minecraft.java:2147)
	at net.minecraft.client.Minecraft.runTick(Minecraft.java:1935)
	at net.minecraft.client.Minecraft.runGameLoop(Minecraft.java:1188)
	at net.minecraft.client.Minecraft.run(Minecraft.java:442)
	at net.minecraft.client.main.Main.main(Main.java:118)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at net.minecraft.launchwrapper.Launch.launch(Launch.java:135)
	at net.minecraft.launchwrapper.Launch.main(Launch.java:28)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at net.minecraftforge.gradle.GradleStartCommon.launch(GradleStartCommon.java:97)
	at GradleStart.main(GradleStart.java:25)